name: ros2-iron-jammy

on:
  push

jobs:
  ros2_iron_jammy_ci:
    name: iron (jammy)
    uses: ./.github/workflows/ros2.yml
    with:
      ROS_DISTRO: iron
      ROS_REPO: testing
      OS_NAME: ubuntu
      OS_CODE_NAME: jammy
      ALLOW_FAIL: false
